mips: smp: fix setup_profiling_timer() prototype
The function is unconditionally defined in smp.c but is conditionally
declared in a header that is not included here.

arch/mips/kernel/smp.c:473:5: error: no previous prototype for 'setup_profiling_timer' [-Werror=missing-prototypes]

Add the missing #include and #ifdef to match the declaration.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>