mips: spram: fix missing prototype warning for spram_config
arch/mips/kernel/spram.c:194:6: error: no previous prototype for 'spram_config' [-Werror=missing-prototypes]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>